# version: '3.8'

services:
  sqlite-db:
    build: 
      context: ./services/sqlite-db
    environment:
      - RUNTIME=docker
    expose:
      - "4000"
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  live-chat:
    build:
      context: ./services/live-chat
    expose:
      - "3003"  
    restart: unless-stopped

  pong-game:
    build:
      context: ./services/pong-game
    expose:
      - "5003"  
    restart: unless-stopped

  auth:
    build:
      context: ./services/auth
    expose:
      - "5000"  
    env_file:
      - ./services/auth/.env
    environment:
      - RUNTIME=docker
    volumes:
      - upload-avatars:/data
    restart: unless-stopped

  web-server:
    build:
      context: ./services/web-server
    environment:
      - RUNTIME=docker
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  api-rest-gateway:
    build:
      context: ./services/api-rest-gateway
    environment:
      - RUNTIME=docker
    expose:
      - "3000"
    restart: unless-stopped

volumes:
  sqlite-data:
  upload-avatars:
