# version: '3.8'

services:
  sqlite-db:
    build: 
      context: ./services/sqlite-db
    env_file:
      - ./services/sqlite-db/.env
    environment:
      - RUNTIME=docker
    expose:
      - "4000"
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  live-chat:
    build:
      context: ./services/live-chat
    expose:
      - "3003"  
    restart: unless-stopped

  auth:
    build:
      context: ./services/auth
    expose:
      - "5000"  
    env_file:
      - ./services/auth/.env
    environment:
      - RUNTIME=docker
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  web-server:
    build:
      context: ./services/web-server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  api-rest-gateway:
    build:
      context: ./services/api-rest-gateway
    env_file:
      - ./services/api-rest-gateway/.env
    environment:
      - RUNTIME=docker
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  sqlite-data:
